/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Model: typeof import('./src/components/Model/Model.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableList: typeof import('./src/components/TableList/TableList.vue')['default']
    Teleports: typeof import('./src/components/Teleports/Teleports.vue')['default']
    Timer: typeof import('./src/components/Timer/Timer.vue')['default']
  }
}
